/**
 * InvestmentOpinion — Styled disclaimer block shown below stock answer bubbles.
 * Renders the labeled "Fintex Investment Opinion" section with a disclaimer.
 * The opinion text itself is already embedded in the markdown answer above.
 * This component adds the visual container and legal disclaimer (Section 7.4).
 */
import { useState } from 'react';
import { TrendingUp, AlertTriangle, ChevronDown, ChevronUp } from 'lucide-react';

interface Props {
  ticker?: string;
}

export default function InvestmentOpinion({ ticker }: Props) {
  const [expanded, setExpanded] = useState(true);

  return (
    <div className="investment-opinion">
      <button
        className="investment-opinion-header"
        onClick={() => setExpanded((v) => !v)}
        aria-expanded={expanded}
      >
        <div className="investment-opinion-title">
          <TrendingUp size={15} className="investment-opinion-icon" />
          <span>Fintex Investment Opinion</span>
          {ticker && (
            <span className="investment-opinion-ticker">{ticker}</span>
          )}
        </div>
        <span className="investment-opinion-toggle">
          {expanded ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
        </span>
      </button>

      {expanded && (
        <div className="investment-opinion-body">
          <div className="investment-opinion-note">
            The investment analysis above is generated by Fintex AI based on
            available financial data, historical price trends, and macroeconomic
            context for Pakistan's financial markets. The opinion considers
            current market sentiment, SBP policy environment, and sector-specific
            factors.
          </div>

          <div className="investment-opinion-disclaimer">
            <AlertTriangle size={12} />
            <span>
              <strong>Disclaimer:</strong> This is an AI-generated opinion for
              educational purposes only. It is not financial advice. Past
              performance is not indicative of future results. Please consult a
              licensed financial advisor before making any investment decisions.
            </span>
          </div>
        </div>
      )}
    </div>
  );
}
