"""
Benchmark 4 — LLM Answer Quality
==================================
Evaluates Fintex-generated answers for:

  • Faithfulness     — claims supported by the retrieved context
  • Answer Relevance — response addresses the question asked
  • Format Compliance— required markdown sections are present
  • Hallucination Guard — forbidden phrases absent from prediction answers
  • Disclaimer Presence  — legal disclaimer always present for stock answers

Uses DeepEval (pip install deepeval) for semantic scoring when available,
with a lightweight rule-based fallback so tests always run offline.

Run:
    pip install deepeval pytest
    pytest tests/test_llm_quality.py -v

Offline (no LLM scoring):
    pytest tests/test_llm_quality.py -v -k "not llm"
"""
import sys, os, re, json
import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

# ── DeepEval guard ────────────────────────────────────────────────────────────
try:
    from deepeval import evaluate
    from deepeval.metrics import (
        FaithfulnessMetric,
        AnswerRelevancyMetric,
        HallucinationMetric,
    )
    from deepeval.test_case import LLMTestCase
    from deepeval.models.base_model import DeepEvalBaseLLM
    import google.generativeai as genai
    HAS_DEEPEVAL = True
except ImportError:
    HAS_DEEPEVAL = False

class GeminiModel(DeepEvalBaseLLM):
    """Custom DeepEval model wrapper to use Gemini instead of OpenAI."""
    def __init__(self, model_name=None):
        from config.settings import get_settings
        settings = get_settings()
        genai.configure(api_key=settings.gemini_api_key)
        # Use explicit models/ prefix and fallback to gemini-flash-latest
        raw_model = model_name or settings.chat_model or "gemini-flash-latest"
        actual_model = f"models/{raw_model}" if not raw_model.startswith("models/") else raw_model
        print(f"\n[DeepEval] Initializing GeminiModel with: {actual_model}")
        self.model = genai.GenerativeModel(actual_model)
        self.model_name = actual_model

    def load_model(self):
        return self.model

    def generate(self, prompt: str) -> str:
        return self.model.generate_content(prompt).text

    async def a_generate(self, prompt: str) -> str:
        res = await self.model.generate_content_async(prompt)
        return res.text

    def get_model_name(self):
        return self.model_name

DEEPEVAL_SKIP = pytest.mark.skipif(
    not HAS_DEEPEVAL, reason="pip install deepeval"
)

# ── Pipeline guard ────────────────────────────────────────────────────────────
def _pipeline_reachable() -> bool:
    try:
        from src.reasoning.fintex_pipeline import FintexPipeline
        return True
    except Exception:
        return False

PIPELINE_SKIP = pytest.mark.skipif(
    not _pipeline_reachable(), reason="Pipeline not importable (check .env / dependencies)"
)


# ── Static answer fixtures (no live calls needed) ────────────────────────────
# These are representative answers generated by the pipeline.
# Rule-based tests run against these strings without any live API call.

SAMPLE_STOCK_ANSWER = """### 📊 Company Background
- **Company:** Engro Corporation (PSX: ENGRO)
- **Sector:** Fertilizers / Conglomerates
- Engro Corporation is one of Pakistan's leading conglomerates with businesses in fertilizers, polymer, energy, and food.

### 📈 Performance Analysis
- ENGRO closed at PKR 285.50 on the latest trading session.
- 30-day change: +4.2% — outperforming the KSE-100 benchmark.
- SBP's 200bps rate cut in April 2025 boosted sentiment in dividend-paying stocks.

### 🧠 Fintex Investment Opinion
ENGRO remains a cornerstone holding for Pakistani investors seeking dividend income. The company's diversified revenue streams and strong fertilizer demand underpin its defensive characteristics. Near-term catalysts include the upcoming Q1 2025 earnings release.

*"This is an AI-generated opinion for educational purposes only. It is not financial advice. Please consult a licensed financial advisor before making investment decisions."*
"""

SAMPLE_PREDICTION_ANSWER = """### 📊 Technical Position — ENGRO
**Latest Price:** PKR 285.50  (as of 2025-05-08)
**Moving Averages:** SMA7 PKR 281.20 ↑1.5% | SMA14 PKR 279.80 ↑2.0% | SMA30 PKR 275.00 ↑3.8%
**RSI (14):** 58.3 — NEUTRAL
**MACD:** +0.4521 | Signal +0.3210 | Histogram +0.1311 [BULLISH]
**Bollinger Bands:** Lower PKR 270.00 | Mid PKR 280.00 | Upper PKR 290.00
**Volume:** +12.5% vs prior period — INCREASING
**Momentum:** 5-day +2.1% | 10-day +3.5%

### 📈 Signal Breakdown
**Bullish (4):**
  - RSI 58.3 — neutral zone (30-70)
  - MACD histogram +0.1311 — bullish momentum
  - SMA7 PKR 281.20 > SMA30 PKR 275.00 — short-term uptrend
  - 5-day momentum +2.1% — buyers in control

### 🔮 Prediction for May 10, 2026
**Verdict:** 📈 **BETTER (Bullish)** — 4/5 signals point upward
**Confidence:** High (80% of indicators in agreement)
**Expected range:** Support PKR 270.00 → Resistance PKR 290.00
**Invalidation trigger:** Close below SMA7 (PKR 281.20) would flip to bearish

### ⚠️ Key Risks
- SBP monetary policy surprise or unexpected interest rate change
- Global commodity price shock or USD/PKR volatility

*This technical analysis is AI-generated for educational purposes only. Past performance does not guarantee future results. Consult a licensed financial advisor before making investment decisions.*
"""

SAMPLE_THEORY_ANSWER = """### 📖 Definition
The Price-to-Earnings (P/E) ratio is the ratio of a company's share price to its earnings per share (EPS), used to value a stock.

### 📝 Detailed Explanation
The P/E ratio helps investors determine the relative value of a company's shares. A high P/E may indicate that investors expect high growth in the future. In Pakistan, P/E ratios of PSX-listed companies typically range from 5x to 20x.

### 🔑 Key Points
- P/E = Share Price / EPS
- Forward P/E uses expected future earnings
- PSX average P/E is approximately 8–10x
- Lower P/E may indicate undervaluation

### 🇵🇰 Pakistan Context
On the PSX, sectors like banking and fertilizers tend to trade at lower P/E multiples due to cyclicality and regulatory constraints.

### 📚 Further Reading
- https://www.psx.com.pk
- https://www.sbp.org.pk
- https://www.investopedia.com/terms/p/price-earningsratio.asp
"""

BAD_PREDICTION_ANSWER = """### 📊 Technical Position Summary
The provided context explicitly states multiple times that it does not contain any technical indicators.

### 📈 Signal Breakdown
Due to the complete absence of specific technical indicators, no signals can be identified.

Direction: Cannot be determined as no technical indicators are available.
Confidence: Cannot be assessed due to the lack of specific indicator readings.
"""

# ── Required sections per answer type ────────────────────────────────────────
REQUIRED_SECTIONS = {
    "stock": ["📊 Company Background", "📈 Performance Analysis", "🧠 Fintex Investment Opinion"],
    "prediction": ["📊 Technical Position", "📈 Signal Breakdown", "🔮 Prediction", "⚠️ Key Risks"],
    "theory": ["📖 Definition", "📝 Detailed Explanation", "🔑 Key Points", "🇵🇰 Pakistan Context", "📚 Further Reading"],
}

DISCLAIMER_PATTERNS = [
    r"educational purposes only",
    r"not financial advice",
    r"consult a licensed financial advisor",
    r"past performance does not guarantee",
]

FORBIDDEN_PREDICTION_PHRASES = [
    "cannot be determined",
    "data is unavailable",
    "no technical indicators",
    "cannot predict",
    "inherently speculative",
    "lack of technical data",
    "absence of specific technical indicators",
]


# ── Rule-based tests (always run — no LLM or API needed) ──────────────────────
class TestFormatCompliance:
    """All required markdown sections must be present."""

    def test_stock_answer_has_all_sections(self):
        for section in REQUIRED_SECTIONS["stock"]:
            assert section in SAMPLE_STOCK_ANSWER, f"Missing section: {section}"

    def test_prediction_answer_has_all_sections(self):
        for section in REQUIRED_SECTIONS["prediction"]:
            assert section in SAMPLE_PREDICTION_ANSWER, f"Missing section: {section}"

    def test_theory_answer_has_all_sections(self):
        for section in REQUIRED_SECTIONS["theory"]:
            assert section in SAMPLE_THEORY_ANSWER, f"Missing section: {section}"

    def test_stock_answer_has_disclaimer(self):
        lower = SAMPLE_STOCK_ANSWER.lower()
        assert any(re.search(p, lower) for p in DISCLAIMER_PATTERNS), \
            "Stock answer missing legal disclaimer"

    def test_prediction_answer_has_disclaimer(self):
        lower = SAMPLE_PREDICTION_ANSWER.lower()
        assert any(re.search(p, lower) for p in DISCLAIMER_PATTERNS), \
            "Prediction answer missing legal disclaimer"


class TestHallucinationGuard:
    """Prediction answers must NEVER contain the 'no data' hedge phrases."""

    def test_good_prediction_has_no_forbidden_phrases(self):
        lower = SAMPLE_PREDICTION_ANSWER.lower()
        for phrase in FORBIDDEN_PREDICTION_PHRASES:
            assert phrase not in lower, \
                f"Forbidden phrase found in good answer: '{phrase}'"

    def test_bad_prediction_detected(self):
        """Confirm the detection works — the known-bad answer should fail."""
        lower = BAD_PREDICTION_ANSWER.lower()
        found = [p for p in FORBIDDEN_PREDICTION_PHRASES if p in lower]
        assert len(found) > 0, "Bad answer detector failed — no forbidden phrases found"

    @pytest.mark.parametrize("phrase", FORBIDDEN_PREDICTION_PHRASES)
    def test_sample_prediction_clean_of_phrase(self, phrase):
        assert phrase not in SAMPLE_PREDICTION_ANSWER.lower(), \
            f"Forbidden phrase '{phrase}' found in prediction answer"


class TestAnswerRelevanceRuleBased:
    """Lightweight relevance checks without an LLM scorer."""

    def test_stock_answer_contains_ticker(self):
        assert "ENGRO" in SAMPLE_STOCK_ANSWER

    def test_stock_answer_contains_price(self):
        assert "PKR" in SAMPLE_STOCK_ANSWER

    def test_prediction_answer_contains_verdict(self):
        assert any(v in SAMPLE_PREDICTION_ANSWER for v in ("BULLISH", "BEARISH", "NEUTRAL", "BETTER", "WORSE"))

    def test_prediction_answer_contains_numeric_rsi(self):
        assert re.search(r"RSI.*\d+\.\d+", SAMPLE_PREDICTION_ANSWER), \
            "Prediction answer missing numeric RSI value"

    def test_theory_answer_contains_formula(self):
        # PE ratio answer should mention the formula
        assert "/" in SAMPLE_THEORY_ANSWER or "formula" in SAMPLE_THEORY_ANSWER.lower()

    def test_theory_answer_contains_pakistan_reference(self):
        lower = SAMPLE_THEORY_ANSWER.lower()
        assert any(w in lower for w in ["pakistan", "psx", "pkr", "sbp"])


class TestPredictionVerdictExtraction:
    """Verify that the verdict line follows the required format."""

    def test_verdict_line_present(self):
        assert "**Verdict:**" in SAMPLE_PREDICTION_ANSWER

    def test_verdict_contains_direction(self):
        verdict_match = re.search(r"\*\*Verdict:\*\*(.+)", SAMPLE_PREDICTION_ANSWER)
        assert verdict_match, "Verdict line not found"
        verdict_text = verdict_match.group(1)
        has_direction = any(d in verdict_text for d in ["BULLISH", "BEARISH", "NEUTRAL", "BETTER", "WORSE"])
        assert has_direction, f"No direction found in verdict: {verdict_text}"

    def test_confidence_line_present(self):
        assert "**Confidence:**" in SAMPLE_PREDICTION_ANSWER

    def test_invalidation_trigger_present(self):
        assert "Invalidation trigger" in SAMPLE_PREDICTION_ANSWER or \
               "invalidation" in SAMPLE_PREDICTION_ANSWER.lower()


# ── Live pipeline tests (hit real API) ───────────────────────────────────────
class TestLiveAnswerQuality:
    """
    Runs real queries through the live Fintex pipeline and asserts format/content.
    Requires backend environment variables (.env) to be configured.
    """

    @PIPELINE_SKIP
    def test_stock_query_format(self):
        from src.reasoning.fintex_pipeline import FintexPipeline
        pipeline = FintexPipeline()
        result = pipeline.answer("What is ENGRO stock?", format="detailed")
        answer = result["answer"]["answer"]
        assert result["category"] == "stocks"
        for section in REQUIRED_SECTIONS["stock"]:
            assert section in answer, f"Live answer missing section: {section}"

    @PIPELINE_SKIP
    def test_prediction_has_no_forbidden_phrases(self):
        from src.reasoning.fintex_pipeline import FintexPipeline
        pipeline = FintexPipeline()
        result = pipeline.answer("Will ENGRO go up tomorrow?")
        answer = result["answer"]["answer"].lower()
        violations = [p for p in FORBIDDEN_PREDICTION_PHRASES if p in answer]
        assert not violations, \
            f"Forbidden phrases found in live prediction: {violations}"

    @PIPELINE_SKIP
    def test_prediction_is_flagged(self):
        from src.reasoning.fintex_pipeline import FintexPipeline
        pipeline = FintexPipeline()
        result = pipeline.answer("Will HBL be bullish next week?")
        assert result.get("is_prediction") is True, \
            "Prediction query not flagged as is_prediction=True"

    @PIPELINE_SKIP
    def test_theory_answer_format(self):
        from src.reasoning.fintex_pipeline import FintexPipeline
        pipeline = FintexPipeline()
        result = pipeline.answer("What is PE ratio?")
        answer = result["answer"]["answer"]
        assert result["category"] == "theory"
        assert "Definition" in answer or "definition" in answer.lower()

    @PIPELINE_SKIP
    def test_off_topic_rejected(self):
        from src.reasoning.fintex_pipeline import FintexPipeline
        pipeline = FintexPipeline()
        result = pipeline.answer("Tell me a cricket joke")
        assert result["category"] == "off_topic"


# ── DeepEval semantic scoring (requires deepeval + OPENAI_API_KEY or local LLM) ─
class TestDeepEvalMetrics:

    @DEEPEVAL_SKIP
    def test_faithfulness(self):
        """Answer claims must be supported by the retrieved context."""
        import time
        time.sleep(30)  # let Gemini RPM quota reset after preceding live pipeline calls
        context = [
            "ENGRO is listed on PSX under ticker ENGRO. Latest close: PKR 285.50.",
            "Engro Corporation operates in fertilizers, polymer, and energy sectors.",
        ]
        test_case = LLMTestCase(
            input="What is ENGRO's latest stock price?",
            actual_output=SAMPLE_STOCK_ANSWER,
            retrieval_context=context,
        )
        model = GeminiModel()
        metric = FaithfulnessMetric(threshold=0.70, model=model)
        try:
            metric.measure(test_case)
        except Exception as e:
            if "429" in str(e) or "ResourceExhausted" in str(e) or "quota" in str(e).lower():
                pytest.skip(f"Gemini Free Tier rate-limit hit — run during off-peak: {e}")
            raise
        assert metric.score >= 0.70, f"Faithfulness score {metric.score:.2f} < 0.70"

    @DEEPEVAL_SKIP
    def test_answer_relevancy(self):
        """Answer must be relevant to the question asked."""
        import time
        time.sleep(30)  # let Gemini RPM quota reset after preceding live pipeline calls
        test_case = LLMTestCase(
            input="What is the PE ratio in Pakistan finance?",
            actual_output=SAMPLE_THEORY_ANSWER,
        )
        model = GeminiModel()
        metric = AnswerRelevancyMetric(threshold=0.70, model=model)
        try:
            metric.measure(test_case)
        except Exception as e:
            if "429" in str(e) or "ResourceExhausted" in str(e) or "quota" in str(e).lower():
                pytest.skip(f"Gemini Free Tier rate-limit hit — run during off-peak: {e}")
            raise
        assert metric.score >= 0.70, f"Relevancy score {metric.score:.2f} < 0.70"

    @DEEPEVAL_SKIP
    def test_hallucination_stock_answer(self):
        """Verify that ENGRO stock answer doesn't hallucinate beyond the context."""
        import time
        time.sleep(30)  # let Gemini RPM quota reset after preceding live pipeline calls
        context = [
            "ENGRO closed at PKR 285.50. 30-day change: +4.2%.",
            "SBP cut rates by 200bps in April 2025.",
        ]
        test_case = LLMTestCase(
            input="Tell me about ENGRO stock performance",
            actual_output=SAMPLE_STOCK_ANSWER,
            context=context,
        )
        model = GeminiModel()
        metric = HallucinationMetric(threshold=0.30, model=model)
        try:
            metric.measure(test_case)
        except Exception as e:
            if "429" in str(e) or "ResourceExhausted" in str(e) or "quota" in str(e).lower():
                pytest.skip(f"Gemini Free Tier rate-limit hit — run during off-peak: {e}")
            raise
        assert metric.score <= 0.30, f"Hallucination score {metric.score:.2f} > 0.30"
